version: '3.8'

services:
  web:
    build: .
    container_name: game-tuoi-tho
    ports:
      - "8080:80"
    volumes:
      - ./web:/usr/share/nginx/html:ro
    restart: unless-stopped
    networks:
      - game-network

networks:
  game-network:
    driver: bridge
