# Netlify Build Configuration
# Đặt file này ở root project

[build]
  # Thư mục chứa file build (web/)
  publish = "web"
  
  # Command để build (không cần vì là static site)
  command = ""

# Cấu hình redirects và rewrites
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers để enable CORS và caching
[[headers]]
  # Apply to all routes
  for = "/*"
  [headers.values]
    # CORS - cho phép load từ mọi domain
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "*"
    
    # Security headers
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "no-referrer-when-downgrade"

[[headers]]
  # Cache game files (JAR, JAD) for 1 year
  for = "/games/*.jar"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/games/*.jad"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Access-Control-Allow-Origin = "*"

[[headers]]
  # Cache static assets for 1 year
  for = "/libjs/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/libmedia/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/libmidi/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  # Don't cache HTML and JSON (always get latest version)
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/games/list.json"
  [headers.values]
    Cache-Control = "public, max-age=300, must-revalidate"
    Access-Control-Allow-Origin = "*"

# Plugin để tối ưu
[[plugins]]
  package = "@netlify/plugin-lighthouse"
